name: canari-sprint
dependencies:
  - python=3.10.12
# jupyter
  - jupyterlab
  - nb_conda_kernels
# dask
  - dask
  - distributed
# computing
  - numpy
  - scipy=1.13
  - numba
  - bottleneck
# netcdf
  - netcdf4
  - xarray[complete]
  - zarr
  - iris
  - cftime
  - intake-xarray
  - cf-python
  - nc-time-axis
# plotting
  - matplotlib
  - cartopy
  - seaborn
  - cmocean
  - cmasher
# regridding
  - esmpy
  - xesmf
  - esmf
# others
  - ipykernel
  - gsw
  - git
  - nco
  - regionmask
  - geopy
  - tqdm
  - aiohttp
  - requests
  - geos
  - shapely
  - pyshp
  - pyjokes 
  - bodc::coast
  - pip
  - pip:
    - numbagg
