name: canari-sprint
dependencies:
  - python=3.10.12
# jupyter
  - jupyterlab=4.1.2
  - nb_conda_kernels=2.3.1
# dask
  - dask=2024.2.1
  - distributed=2024.2.1
# computing
  - numpy=1.26.4
  - scipy=1.12.0
  - numba=0.59.0
  - bottleneck=1.3.8
# netcdf
  - netcdf4=1.6.5
  - xarray[complete]=2024.2.0
  - zarr=2.17.0
  - iris=3.8.0
  - cftime=1.6.3
  - intake-xarray=0.7.0
  - cf-python=3.16.0
  - nc-time-axis=1.4.1
# plotting
  - matplotlib=3.8.3
  - cartopy=0.22.0
  - seaborn=0.13.2
  - cmocean=3.1.3
  - cmasher=1.8.0
# regridding
  - esmpy=8.6.0
  - xesmf=0.8.4
  - esmf=8.6.0
# others
  - ipykernel=6.29.3
  - gsw=3.6.17
  - git=2.43.0
  - nco=5.2.1
  - regionmask=0.11.0
  - geopy=2.4.1
  - tqdm=4.66.2
  - aiohttp=3.9.3
  - requests=2.31.0
  - geos=3.12.1
  - shapely=2.0.3
  - pyshp=2.3.1
  - pyjokes=0.6.0
  - bodc::coast=3.3.0
  - pip=24.0
  - pip:
    - numbagg==0.8.0
